feat(FEC-13461): add support for seekFrom clipTo
kaltura/playkit-js-share pull request #34
Opened 2023-11-30 09:35 UTC by lianbenjamin

### Description of the Changes

add support for seekFrom and clipTo in share overlay.

Solves FEC-13461

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-11-30 10:47 UTC, SivanA-Kaltura requested changes

2023-11-30 10:47 UTC, SivanA-Kaltura commented on translations/en.i18n.json
> +      "full_video": "Full video",
please add a ticket for i18n if there isn't one yet

2023-11-30 10:47 UTC, SivanA-Kaltura commented on src/components/share-overlay/share-overlay.js
> +    cb(formattedInput);
use a variable name that explains what the callback function does

2023-11-30 11:20 UTC, lianbenjamin commented on src/components/share-overlay/share-overlay.js
> +        <input
for a11y.. radio button should be composed out of input and label elements.

2023-12-03 09:01 UTC, SivanA-Kaltura submitted a review, later dismissed

2023-12-03 10:35 UTC, merged